# Generated by Django 4.1.4 on 2022-12-15 08:52

import django.core.validators
from django.db import migrations, models
import exam_prep_web_basics_2.my_music_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, unique=True)),
                ('album_artist', models.CharField(max_length=30)),
                ('album_genre', models.CharField(choices=[('Pop Music', 'Pop Music'), ('Jazz Music', 'Jazz Music'), ('R&B Music', 'R&B Music'), ('Rock Music', 'Rock Music'), ('Country Music', 'Country Music'), ('Dance Music', 'Dance Music'), ('Hip Hop Music', 'Hip Hop Music'), ('Other', 'Other')], max_length=30)),
                ('album_description', models.TextField(blank=True, null=True)),
                ('album_image_url', models.URLField()),
                ('album_price', models.FloatField(validators=[exam_prep_web_basics_2.my_music_app.validators.float_above_zero])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), exam_prep_web_basics_2.my_music_app.validators.text_validator])),
                ('profile_email', models.EmailField(max_length=254)),
                ('profile_age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
